package cayetano.demo.kie_demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Transaction implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Double amount;

    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer status;

    public Transaction() {
    }
    
    public Transaction(java.lang.Integer status, java.lang.Double amount) {
        this.status = status;
        this.amount = amount;
    }

    public java.lang.Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(java.lang.Double amount) {
        this.amount = amount;
    }

    public java.lang.Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(java.lang.Integer status) {
        this.status = status;
    }

}