package cayetano.demo.kie_demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Transaction implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Position(1)
	private java.lang.Double amount;

    @org.kie.api.definition.type.Position(0)
	private java.lang.Integer status;

    @org.kie.api.definition.type.Position(value = 2)
	private java.lang.Integer type;

	public java.lang.Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(java.lang.Double amount) {
        this.amount = amount;
    }

    public java.lang.Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(java.lang.Integer status) {
        this.status = status;
    }

	public java.lang.Integer getType() {
		return this.type;
	}

	public void setType(java.lang.Integer type) {
		this.type = type;
	}

	public Transaction() {
	}

	public Transaction(java.lang.Integer status, java.lang.Double amount,
			java.lang.Integer type) {
		this.status = status;
		this.amount = amount;
		this.type = type;
	}

}